//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanterBrain_Buddy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("placeholder")]
        public string VoiceInput {
            get {
                return ((string)(this["VoiceInput"]));
            }
            set {
                this["VoiceInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("placeholder")]
        public string PTTHotkey {
            get {
                return ((string)(this["PTTHotkey"]));
            }
            set {
                this["PTTHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("placeholder")]
        public string STTProvider {
            get {
                return ((string)(this["STTProvider"]));
            }
            set {
                this["STTProvider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("placeholder")]
        public string LLMProvider {
            get {
                return ((string)(this["LLMProvider"]));
            }
            set {
                this["LLMProvider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("placeholder")]
        public string LLMModel {
            get {
                return ((string)(this["LLMModel"]));
            }
            set {
                this["LLMModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("placeholder")]
        public string LLMRoleText {
            get {
                return ((string)(this["LLMRoleText"]));
            }
            set {
                this["LLMRoleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("placeholder")]
        public string TTSProvider {
            get {
                return ((string)(this["TTSProvider"]));
            }
            set {
                this["TTSProvider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("placeholder")]
        public string TTSAudioOutput {
            get {
                return ((string)(this["TTSAudioOutput"]));
            }
            set {
                this["TTSAudioOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("placeholder")]
        public string TTSAudioVoice {
            get {
                return ((string)(this["TTSAudioVoice"]));
            }
            set {
                this["TTSAudioVoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("placeholder")]
        public string TTSAudioVoiceOptions {
            get {
                return ((string)(this["TTSAudioVoiceOptions"]));
            }
            set {
                this["TTSAudioVoiceOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("placeholder")]
        public string STTAPIKey {
            get {
                return ((string)(this["STTAPIKey"]));
            }
            set {
                this["STTAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("placeholder")]
        public string STTAPIRegion {
            get {
                return ((string)(this["STTAPIRegion"]));
            }
            set {
                this["STTAPIRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("placeholder")]
        public string LLMAPIKey {
            get {
                return ((string)(this["LLMAPIKey"]));
            }
            set {
                this["LLMAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TTSAudioVoiceEnabled {
            get {
                return ((bool)(this["TTSAudioVoiceEnabled"]));
            }
            set {
                this["TTSAudioVoiceEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TTSAudioVoiceOptionsEnabled {
            get {
                return ((bool)(this["TTSAudioVoiceOptionsEnabled"]));
            }
            set {
                this["TTSAudioVoiceOptionsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool STTAPIKeyEnabled {
            get {
                return ((bool)(this["STTAPIKeyEnabled"]));
            }
            set {
                this["STTAPIKeyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool STTAPIRegionEnabled {
            get {
                return ((bool)(this["STTAPIRegionEnabled"]));
            }
            set {
                this["STTAPIRegionEnabled"] = value;
            }
        }
    }
}
